package View;

import Paineis.MudaPainel;
import Paineis.PnlTransferir;

public class InterfaceUsuario extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceUsuario
     */
    public InterfaceUsuario() {
        initComponents();

        new MudaPainel(pnlMuda, new Paineis.Inicial());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Case1 = new customButton.customButton();
        Case2 = new customButton.customButton();
        Case3 = new customButton.customButton();
        Case4 = new customButton.customButton();
        Case5 = new customButton.customButton();
        Case6 = new customButton.customButton();
        Case7 = new customButton.customButton();
        Case8 = new customButton.customButton();
        Case9 = new customButton.customButton();
        Case10 = new customButton.customButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlMuda = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Case1.setBackground(new java.awt.Color(0, 153, 153));
        Case1.setText("Cadastrar Cliente");
        Case1.setColorHover(new java.awt.Color(0, 102, 102));
        Case1.setColorNormal(new java.awt.Color(0, 153, 153));
        Case1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Case1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case1ActionPerformed(evt);
            }
        });

        Case2.setBackground(new java.awt.Color(0, 153, 153));
        Case2.setText("Cadastrar Conta");
        Case2.setColorHover(new java.awt.Color(0, 102, 102));
        Case2.setColorNormal(new java.awt.Color(0, 153, 153));
        Case2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Case2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case2ActionPerformed(evt);
            }
        });

        Case3.setBackground(new java.awt.Color(0, 153, 153));
        Case3.setText("Listar Conta");
        Case3.setColorHover(new java.awt.Color(0, 102, 102));
        Case3.setColorNormal(new java.awt.Color(0, 153, 153));
        Case3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Case3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case3ActionPerformed(evt);
            }
        });

        Case4.setBackground(new java.awt.Color(0, 153, 153));
        Case4.setText("Pesquisar Conta");
        Case4.setColorHover(new java.awt.Color(0, 102, 102));
        Case4.setColorNormal(new java.awt.Color(0, 153, 153));
        Case4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        Case5.setBackground(new java.awt.Color(0, 153, 153));
        Case5.setText("Depositar");
        Case5.setColorHover(new java.awt.Color(0, 102, 102));
        Case5.setColorNormal(new java.awt.Color(0, 153, 153));
        Case5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Case5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case5ActionPerformed(evt);
            }
        });

        Case6.setBackground(new java.awt.Color(0, 153, 153));
        Case6.setText("Debitar (Sacar)");
        Case6.setColorHover(new java.awt.Color(0, 102, 102));
        Case6.setColorNormal(new java.awt.Color(0, 153, 153));
        Case6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Case6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case6ActionPerformed(evt);
            }
        });

        Case7.setBackground(new java.awt.Color(0, 153, 153));
        Case7.setText("Transferir");
        Case7.setColorHover(new java.awt.Color(0, 102, 102));
        Case7.setColorNormal(new java.awt.Color(0, 153, 153));
        Case7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Case7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case7ActionPerformed(evt);
            }
        });

        Case8.setBackground(new java.awt.Color(0, 153, 153));
        Case8.setText("Remover (Conta)");
        Case8.setColorHover(new java.awt.Color(0, 102, 102));
        Case8.setColorNormal(new java.awt.Color(0, 153, 153));
        Case8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Case8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case8ActionPerformed(evt);
            }
        });

        Case9.setBackground(new java.awt.Color(0, 153, 153));
        Case9.setText("Sair");
        Case9.setColorHover(new java.awt.Color(0, 102, 102));
        Case9.setColorNormal(new java.awt.Color(0, 153, 153));
        Case9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Case9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case9ActionPerformed(evt);
            }
        });

        Case10.setBackground(new java.awt.Color(0, 153, 153));
        Case10.setText("Inicio");
        Case10.setColorHover(new java.awt.Color(0, 102, 102));
        Case10.setColorNormal(new java.awt.Color(0, 153, 153));
        Case10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Case10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Case9, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(Case8, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(Case7, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(Case6, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(Case5, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(Case4, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(Case3, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(Case2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(Case1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(Case10, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Case10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Case1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Case2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Case3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Case4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Case5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Case6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Case7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Case8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Case9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(null);

        pnlMuda.setBackground(new java.awt.Color(255, 255, 255));
        pnlMuda.setLayout(new javax.swing.BoxLayout(pnlMuda, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane2.setViewportView(pnlMuda);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Case9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case9ActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_Case9ActionPerformed

    private void Case1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case1ActionPerformed
        new MudaPainel(pnlMuda, new Paineis.CadCliente());
    }//GEN-LAST:event_Case1ActionPerformed

    private void Case2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case2ActionPerformed
        new MudaPainel(pnlMuda, new Paineis.CadConta());
    }//GEN-LAST:event_Case2ActionPerformed

    private void Case3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case3ActionPerformed
        new MudaPainel(pnlMuda, new Paineis.ListaConta());
    }//GEN-LAST:event_Case3ActionPerformed

    private void Case5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case5ActionPerformed
        new MudaPainel(pnlMuda, new Paineis.PnlDepositar());       
    }//GEN-LAST:event_Case5ActionPerformed

    private void Case6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case6ActionPerformed
        new MudaPainel(pnlMuda, new Paineis.pnlSacar());
    }//GEN-LAST:event_Case6ActionPerformed

    private void Case7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case7ActionPerformed
        new MudaPainel(pnlMuda, new Paineis.PnlTransferir());
    }//GEN-LAST:event_Case7ActionPerformed

    private void Case8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case8ActionPerformed
        new MudaPainel(pnlMuda, new Paineis.PnlRemover());
    }//GEN-LAST:event_Case8ActionPerformed

    private void Case10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case10ActionPerformed
        new MudaPainel(pnlMuda, new Paineis.Inicial());
    }//GEN-LAST:event_Case10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customButton.customButton Case1;
    private customButton.customButton Case10;
    private customButton.customButton Case2;
    private customButton.customButton Case3;
    private customButton.customButton Case4;
    private customButton.customButton Case5;
    private customButton.customButton Case6;
    private customButton.customButton Case7;
    private customButton.customButton Case8;
    private customButton.customButton Case9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlMuda;
    // End of variables declaration//GEN-END:variables
}
